name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  shellspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install shellspec
        run: |
          curl -fsSL https://git.io/shellspec | sh -s -- --yes
          echo "$HOME/.local/lib/shellspec" >> "$GITHUB_PATH"

      - name: Run tests
        run: shellspec -t tap
